/**
 * Realistic Indian Tech Job Dataset
 * 60 unique listings across diverse roles and companies.
 */

const allJobs = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k–₹60k/month Internship",
        applyUrl: "https://amazon.jobs/en/jobs/245123",
        description: "Join our core fulfillment team to build scalable services. You will work on high-availability systems using AWS and Java. Perfect for early-career engineers looking for scale."
    },
    {
        id: 2,
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Pune",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C++", "Python", "SQL"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://www.tcs.com/careers",
        description: "Entry-level role for talented graduates. You will undergo rigorous training in digital technologies before being deployed to global banking projects."
    },
    {
        id: 3,
        title: "Frontend Intern (React)",
        company: "Razorpay",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "JavaScript", "Tailwind CSS"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹25k–₹35k/month Internship",
        applyUrl: "https://razorpay.com/jobs",
        description: "Build the next generation of fintech dashboards. Focus on accessibility, performance, and clean UI components in a fast-paced environment."
    },
    {
        id: 4,
        title: "Java Developer",
        company: "Infosys",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Spring Boot", "Microservices", "REST API"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "4.5–6 LPA",
        applyUrl: "https://infosys.com/careers",
        description: "Modernize legacy systems using Spring Cloud and Java 17. Great opportunity to work on large-scale enterprise transformations for US-based clients."
    },
    {
        id: 5,
        title: "React Developer",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "TypeScript", "Redux"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        applyUrl: "https://cred.club/careers",
        description: "High-performance UI engineering for India's most design-focused startup. You value aesthetics as much as clean code and state management efficiency."
    },
    {
        id: 6,
        title: "Backend Developer (Node.js)",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Node.js", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "10–16 LPA",
        applyUrl: "https://swiggy.com/careers",
        description: "Help optimize logistics and delivery routes for millions of weekly orders. Work on low-latency systems and distributed microservices architecture."
    },
    {
        id: 7,
        title: "QA Automation Intern",
        company: "Accenture",
        location: "Chennai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Selenium", "Java", "TestNG"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "₹20k–₹30k/month Internship",
        applyUrl: "https://accenture.com/careers",
        description: "Support our quality assurance transformation for a global retail giant. Write automated test scripts and learn CI/CD pipelines."
    },
    {
        id: 8,
        title: "Python Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Django", "JavaScript"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "6–9 LPA",
        applyUrl: "https://zoho.com/careers",
        description: "Build world-class SaaS products from the ground up. You'll contribute to our core office suite apps and scale them for global users."
    },
    {
        id: 9,
        title: "Data Analyst Trainee",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "PowerBI", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://flipkart.com/careers",
        description: "Dive into big data and surface actionable insights for the marketing team. Learn to bridge the gap between business objectives and data science."
    },
    {
        id: 10,
        title: "Software Engineer (Full Stack)",
        company: "PhonePe",
        location: "Pune",
        mode: "Remote",
        experience: "1-3",
        skills: ["Go", "React Native", "Kafka"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "14–22 LPA",
        applyUrl: "https://phonepe.com/careers",
        description: "Join the digital payments revolution. Build reliable mobile and web interfaces that handle billions of transactions with zero downtime."
    },
    {
        id: 11,
        title: "Junior Backend Eng",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Haskell", "PureScript", "Functional Programming"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "12–15 LPA",
        applyUrl: "https://juspay.in/careers",
        description: "For those who love deep engineering. Help us build the backbone of India's payment ecosystem using functional programming paradigms."
    },
    {
        id: 12,
        title: "Full Stack Intern",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Ruby on Rails", "React", "PostgreSQL"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://freshworks.com/careers",
        description: "Learn how to build customer-centric software. Work alongside experienced engineers to ship features that impact over 50k customers globally."
    },
    {
        id: 13,
        title: "DevOps Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kubernetes", "Docker", "Terraform"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "9–14 LPA",
        applyUrl: "https://paytm.com/careers",
        description: "Automate and scale infrastructure for high-traffic financial services. Focus on security, observability, and high-availability cloud deployments."
    },
    {
        id: 14,
        title: "Mobile Dev (iOS/Swift)",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Swift", "SwiftUI", "Combine"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "15–20 LPA",
        applyUrl: "https://zomato.com/careers",
        description: "Craft seamless food ordering experiences. You will improve the performance and smoothness of our main iOS app used by millions."
    },
    {
        id: 15,
        title: "Associate Analyst",
        company: "Wipro",
        location: "Kolkata",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Excel", "Tableau", "Statistical Analysis"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://wipro.com/careers",
        description: "Support our data governance and business intelligence units. Transform raw enterprise data into meaningful executive reports."
    },
    {
        id: 16,
        title: "Security Engineer",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Cyber Security", "Python", "Cloud Security"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "8–13 LPA",
        applyUrl: "https://ibm.com/careers",
        description: "Protect global enterprise assets. You will perform vulnerability assessments and design secure network architectures for hybrid cloud environments."
    },
    {
        id: 17,
        title: "React Native Developer",
        company: "ZestMoney",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "11–16 LPA",
        applyUrl: "https://zestmoney.in/careers",
        description: "Build beautiful and performant fintech apps for everyone. Focus on cross-platform efficiency and high-fidelity mobile interactions."
    },
    {
        id: 18,
        title: "Graduate Trainee (QA)",
        company: "Cognizant",
        location: "Coimbatore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "SQL", "Java"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "4–5.5 LPA",
        applyUrl: "https://cognizant.com/careers",
        description: "Start your career in quality engineering. Learn modern testing methodologies and support global healthcare and insurance projects."
    },
    {
        id: 19,
        title: "Junior Data Engineer",
        company: "Dell",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["PySpark", "Hadoop", "SQL"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "7–11 LPA",
        applyUrl: "https://dell.com/careers",
        description: "Build robust data pipelines for manufacturing analytics. Process petabytes of data to optimize supply chain efficiencies across Asia."
    },
    {
        id: 20,
        title: "SDE-1 (Java)",
        company: "Oracle",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Oracle DB", "Microservices"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "14–20 LPA",
        applyUrl: "https://oracle.com/careers",
        description: "Direct contribution to enterprise cloud services. Optimize heavy-lifting database interactions and scale back-end infrastructure."
    },
    {
        id: 21,
        title: "Cloud Support Assoc",
        company: "Amazon Web Services",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Networking", "Linux", "Cloud Computing"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "12–16 LPA",
        applyUrl: "https://aws.amazon.com/careers",
        description: "Solve complex technical challenges for global AWS customers. You'll dive deep into infrastructure, networking, and cloud architecture."
    },
    {
        id: 22,
        title: "Junior Product Manager",
        company: "Slice",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Product Analytics", "SQL", "Stakeholder Mgmt"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–15 LPA",
        applyUrl: "https://sliceit.com/careers",
        description: "Ship products that redefine credit for Gen-Z. You’ll work at the intersection of design, engineering, and business strategy."
    },
    {
        id: 23,
        title: "Android Intern",
        company: "Ola",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Kotlin", "Android SDK", "Jetpack Compose"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://ola.in/careers",
        description: "Help build the future of urban mobility. Work on the core Ola app and improve real-time tracking and payment integrations."
    },
    {
        id: 24,
        title: "System Engineer",
        company: "SAP",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Abap", "Java", "Hana"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "9–14 LPA",
        applyUrl: "https://sap.com/careers",
        description: "Develop enterprise software that powers the world's largest companies. Focus on sustainability and modern ERP solutions."
    },
    {
        id: 25,
        title: "Data Science Intern",
        company: "Fractal Analytics",
        location: "Mumbai",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Machine Learning", "R", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://fractal.ai/careers",
        description: "Apply cutting-edge AI to real-world problems. Learn from world-class data scientists and help clients make better decisions with data."
    },
    {
        id: 26,
        title: "Blockchain developer",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Solidity", "Rust", "Ethereum"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–25 LPA",
        applyUrl: "https://polygon.technology/careers",
        description: "Scale Ethereum for the next billion users. Work on ZK-rollups and core protocol improvements in a globally distributed team."
    },
    {
        id: 27,
        title: "PHP Developer",
        company: "IndiaMART",
        location: "Noida",
        mode: "Onsite",
        experience: "0-1",
        skills: ["PHP", "MySQL", "jQuery"],
        source: "Naukri",
        postedDaysAgo: 10,
        salaryRange: "4–7 LPA",
        applyUrl: "https://indiamart.com/careers",
        description: "Maintain and scale India's largest B2B marketplace. Optimize legacy codebases and implement new features for millions of SMEs."
    },
    {
        id: 28,
        title: "Embedded Systems Eng",
        company: "Ather Energy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Embedded C", "RTOS", "Electronics"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "10–17 LPA",
        applyUrl: "https://atherenergy.com/careers",
        description: "Write code that moves hardware. Develop firmware for the next generation of electric scooters and optimize battery management systems."
    },
    {
        id: 29,
        title: "Content Strategist",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["SEO", "Content Writing", "Social Media"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "6–10 LPA",
        applyUrl: "https://unacademy.com/careers",
        description: "Create engaging educational content for millions of learners. Drive impact through storytelling and data-driven content marketing."
    },
    {
        id: 30,
        title: "Junior UI Designer",
        company: "Licious",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Figma", "Design Systems", "Prototyping"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "7–12 LPA",
        applyUrl: "https://licious.in/careers",
        description: "Design delightful food commerce experiences. You'll work on the visual identity and user interface of our award-winning mobile app."
    },
    {
        id: 31,
        title: "Network Engineer",
        company: "Cisco",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["CCNA", "Networking", "Python"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "10–15 LPA",
        applyUrl: "https://cisco.com/careers",
        description: "Build the hardware and software that powers the internet. Focus on network security and software-defined networking."
    },
    {
        id: 32,
        title: "Graduate Engineer",
        company: "L&T Infotech",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "DotNet"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "4–5 LPA",
        applyUrl: "https://lntinfotech.com/careers",
        description: "Join our global IT infrastructure projects. You will be trained in enterprise technologies and support digital transformation initiatives."
    },
    {
        id: 33,
        title: "Product Analyst",
        company: "Meesho",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["SQL", "Data Visualization", "Experimentation"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        applyUrl: "https://meesho.io/careers",
        description: "Drive e-commerce growth through data. You'll analyze user behavior and help product teams make data-backed decisions to social commerce."
    },
    {
        id: 34,
        title: "Full Stack Developer",
        company: "Groww",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Spring Boot", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–25 LPA",
        applyUrl: "https://groww.in/careers",
        description: "Democratize investing for billions. Build simple and intuitive financial tools for the next generation of Indian investors."
    },
    {
        id: 35,
        title: "Backend Intern (Go)",
        company: "CoinSwitch",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Go", "Redis", "Microservices"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://coinswitch.co/careers",
        description: "Learn how to build high-scale crypto exchange infrastructure. Focus on reliability, transaction security, and low-latency API design."
    },
    {
        id: 36,
        title: "Salesforce Developer",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Salesforce", "Apex", "LWC"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "8–13 LPA",
        applyUrl: "https://deloitte.com/careers",
        description: "Deliver world-class CRM solutions. You'll help global clients transform their sales and service processes using the Salesforce ecosystem."
    },
    {
        id: 37,
        title: "Site Reliability Eng",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "AWS", "Monitoring"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        applyUrl: "https://dunzo.com/careers",
        description: "Keep the delivery engine running 24/7. You will work on automation, incident management, and performance tuning for critical services."
    },
    {
        id: 38,
        title: "Junior Game Developer",
        company: "Nazara",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Unity", "C#", "Game Design"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "6–10 LPA",
        applyUrl: "https://nazara.com/careers",
        description: "Build games that millions love to play. You'll contribute to our portfolio of mobile games and help design engaging gameplay mechanics."
    },
    {
        id: 39,
        title: "Front-end Developer",
        company: "CureFit",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React Native", "CSS", "UI/UX"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–16 LPA",
        applyUrl: "https://cult.fit/careers",
        description: "Make health and fitness intuitive. Work on high-quality mobile and web apps that inspire users to stay active and healthy."
    },
    {
        id: 40,
        title: "Hardware Designer",
        company: "Boat",
        location: "Delhi",
        mode: "Onsite",
        experience: "1-3",
        skills: ["PCB Design", "Circuitry", "Product Design"],
        source: "Indeed",
        postedDaysAgo: 9,
        salaryRange: "8–12 LPA",
        applyUrl: "https://boat-lifestyle.com/careers",
        description: "Design the future of consumer audio. You'll work on the engineering and visual design of our next-gen headphones and speakers."
    },
    {
        id: 41,
        title: "Security Analyst",
        company: "PayU",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Hacking", "Compliance", "Network Security"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "7–11 LPA",
        applyUrl: "https://payu.in/careers",
        description: "Secure the payments ecosystem. You'll monitor for threats, conduct security audits, and ensure compliance with global financial standards."
    },
    {
        id: 42,
        title: "ML Engineering Intern",
        company: "InMobi",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Deep Learning", "Python", "PyTorch"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k–₹55k/month Internship",
        applyUrl: "https://inmobi.com/careers",
        description: "Work on cutting-edge ad-tech algorithms. You'll build machine learning models to improve ad relevance and user engagement at massive scale."
    },
    {
        id: 43,
        title: "QA Engineer (Manual)",
        company: "Byju's",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Blackbox Testing", "Jira", "Mobile Testing"],
        source: "Indeed",
        postedDaysAgo: 8,
        salaryRange: "5–8 LPA",
        applyUrl: "https://byjus.com/careers",
        description: "Ensure the highest quality for educational apps. You'll find bugs, write test cases, and help ship seamless learning experiences to students."
    },
    {
        id: 44,
        title: "System Admin (Linux)",
        company: "Hostinger",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Bash", "Linux", "Server Management"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "6–10 LPA",
        applyUrl: "https://hostinger.in/careers",
        description: "Manage servers for millions of users worldwide. You'll focus on uptime, performance optimization, and automation of server tasks."
    },
    {
        id: 45,
        title: "Copywriter (Intern)",
        company: "Publicis",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Writing", "Creativity", "Marketing"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://publicisgroupe.com/careers",
        description: "Join a world-class advertising agency. You'll write catchy headlines, social media copy, and help brainstorm campaigns for top brands."
    },
    {
        id: 46,
        title: "HR Ops Coordinator",
        company: "Genpact",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Onboarding", "Communication", "Excel"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "4–6 LPA",
        applyUrl: "https://genpact.com/careers",
        description: "Support our growing workforce. You'll handle employee onboarding, manage records, and ensure a smooth experience for new hires."
    },
    {
        id: 47,
        title: "Sales Exec (B2B)",
        company: "Hubilo",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["B2B Sales", "Lead Generation", "Communication"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "8–12 LPA + Incentives",
        applyUrl: "https://hubilo.com/careers",
        description: "Drive growth for an events platform. You'll reach out to potential clients, pitch our products, and close deals in a global market."
    },
    {
        id: 48,
        title: "Project Coordinator",
        company: "Mindtree",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Agile", "Jira", "Project Management"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "7–10 LPA",
        applyUrl: "https://mindtree.com/careers",
        description: "Help manage complex software projects. You'll coordinate between teams, track progress, and ensure deadlines are met using Agile."
    },
    {
        id: 49,
        title: "Accountant (Junior)",
        company: "PwC India",
        location: "Mumbai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Tally", "Taxation", "Audit"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "5–8 LPA",
        applyUrl: "https://pwc.in/careers",
        description: "Start your finance career with the big four. You'll assist in auditing, tax compliance, and managing accounts for enterprise clients."
    },
    {
        id: 50,
        title: "Customer Success",
        company: "Chargebee",
        location: "Chennai",
        mode: "Remote",
        experience: "1-3",
        skills: ["SaaS", "Customer Support", "CRM"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "9–14 LPA",
        applyUrl: "https://chargebee.com/careers",
        description: "Help our customers get the most out of our subscription billing platform. You'll build relationships and drive product adoption."
    },
    {
        id: 51,
        title: "React Developer",
        company: "Nykaa",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "CSS-in-JS", "Next.js"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–15 LPA",
        applyUrl: "https://nykaa.com/careers",
        description: "Build beautiful shopping experiences for the beauty industry. You'll work on the core web platform and high-conversion landing pages."
    },
    {
        id: 52,
        title: "Data Analyst",
        company: "BigBasket",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["SQL", "Python", "Tableau"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "8–12 LPA",
        applyUrl: "https://bigbasket.com/careers",
        description: "Optimize the supply chain of India's largest online grocer. Use data to predict demand and reduce delivery times across major cities."
    },
    {
        id: 53,
        title: "Backend Dev",
        company: "Upstox",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kotlin", "Java", "PostgreSQL"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "12–18 LPA",
        applyUrl: "https://upstox.com/careers",
        description: "Build the engines that power the Indian stock market. You'll focus on transaction speed, security, and the reliability of trading systems."
    },
    {
        id: 54,
        title: "Marketing Intern",
        company: "Mamaearth",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Social Media", "Canva", "Communication"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹12k–₹20k/month Internship",
        applyUrl: "https://mamaearth.in/careers",
        description: "Support our digital marketing and brand awareness campaigns. You'll help with social media posts and event coordination."
    },
    {
        id: 55,
        title: "Growth Manager",
        company: "Delhivery",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Strategic Ops", "Data Analysis", "Communication"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "12–18 LPA",
        applyUrl: "https://delhivery.com/careers",
        description: "Lead logistics expansion and efficiency. You'll identify growth opportunities and execute strategies to scale our network across India."
    },
    {
        id: 56,
        title: "Node.js Developer",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Node.js", "API Design", "Security"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "18–28 LPA",
        applyUrl: "https://postman.com/careers",
        description: "Build tools that every developer uses. You'll work on the core API platform and improve our developer experience worldwide."
    },
    {
        id: 57,
        title: "Graphic Designer",
        company: "Myntra",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Adobe Suite", "Creative Design", "Aesthetics"],
        source: "Indeed",
        postedDaysAgo: 8,
        salaryRange: "7–11 LPA",
        applyUrl: "https://myntra.com/careers",
        description: "Design the visual voice of fashion e-commerce. You'll create banners, social assets, and campaign looks for our top fashion brands."
    },
    {
        id: 58,
        title: "Android Developer",
        company: "Pharmeasy",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kotlin", "Android SDK", "Firebase"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "10–15 LPA",
        applyUrl: "https://pharmeasy.in/careers",
        description: "Improve health delivery across India. Scale our medicine ordering app and focus on seamless UX and real-time order tracking."
    },
    {
        id: 59,
        title: "Technical Writer",
        company: "HCL Tech",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Writing", "Documentation", "Knowledge Mgmt"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "6–9 LPA",
        applyUrl: "https://hcltech.com/careers",
        description: "Translate complex tech into clear guides. You'll work with engineering teams to document software architecture and APIs for global users."
    },
    {
        id: 60,
        title: "Business Analyst",
        company: "InCred",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["BA Methodologies", "SQL", "Excel"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "8–13 LPA",
        applyUrl: "https://incred.com/careers",
        description: "Bridge the gap between tech and finance. Analyze credit risk and business flows to improve our digital lending platforms."
    }
];

// Export for use in app.js
window.allJobs = allJobs;
